name: template

on:
  workflow_call:
    inputs:
      NAME:
        required: true
        type: string
      PRODUCT:
        required: true
        type: string

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Check CDN and latest release versions
      id: check
      run: |
        product=${{ inputs.NAME }}
        latest_branch="release/${product}_latest"
        latest_build=$(curl -s "http://us.patch.battle.net:1119/${{ inputs.PRODUCT }}/versions" | awk -F '|' '$1 == "us" {print $6}')
        latest_build_number=$(echo ${latest_build} | awk -F '.' '{print $NF}')
        echo "CDN -> ${latest_build} (${latest_build_number})"
        latest_commit_build=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${latest_branch}" | grep -oP '(?<="message": ")[^"]*' | sed -E "s/${product} ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/\1/")
        latest_commit_build_number=$(echo ${latest_commit_build} | awk -F '.' '{print $NF}')
        echo "${latest_branch} -> ${latest_commit_build} (${latest_commit_build_number})"
        if [[ ! "${latest_build_number}" =~ ^[0-9]+$ ]]; then
          echo "Unable to extract build from CDN."
          echo "skip=true" >> $GITHUB_OUTPUT
        elif [[ ! "${latest_commit_build_number}" =~ ^[0-9]+$ ]]; then
          echo "Unable to extract build from ${latest_branch}."
          echo "skip=true" >> $GITHUB_OUTPUT
        elif [[ "${latest_commit_build_number}" -ge "${latest_build_number}" ]]; then
          echo "${latest_branch} is already up-to-date."
          echo "skip=true" >> $GITHUB_OUTPUT
        fi

    - name: Setup Lua and LuaRocks
      if: ${{ steps.check.outputs.skip != 'true' }}
      uses: ljmf00/setup-lua@v1.0.0
      with:
        lua-version: '5.1.5'
        install-luarocks: true

    - name: Setup lua-zip
      if: ${{ steps.check.outputs.skip != 'true' }}
      run: |
        sudo apt-get install libzip-dev
        luarocks install --server=http://luarocks.org/dev lua-zip

    - name: Setup wowcig
      if: ${{ steps.check.outputs.skip != 'true' }}
      run: luarocks install wowcig 0.16.3-0

    - name: Apply hotfix to luadbd
      if: ${{ steps.check.outputs.skip != 'true' }}
      run: |
        luafile=$(find $HOME -type f -path '*/luadbd/dbds.lua')
        if [ -z "$luafile" ]; then
          echo "Unable to find the relevant file."
        else
          echo "Patching: $luafile"
          sed -i 's|https://raw.githubusercontent.com/wowdev/wow-listfile/master/community-listfile.csv|https://github.com/wowdev/wow-listfile/releases/latest/download/community-listfile.csv|' "$luafile"
        fi

    - name: Run wowcig on ${{ inputs.NAME }}
      if: ${{ steps.check.outputs.skip != 'true' }}
      run: |
        wowcig --db2 all --skip-framexml --product ${{ inputs.PRODUCT }}
        tree "extracts/${{ inputs.PRODUCT }}/db2"

    - name: Setup .NET 7
      if: ${{ steps.check.outputs.skip != 'true' }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Download latest DBC2CSV release
      if: ${{ steps.check.outputs.skip != 'true' }}
      uses: robinraju/release-downloader@v1.10
      with:
        repository: 'Marlamin/DBC2CSV'
        latest: true
        fileName: '.*linux.*'

    - name: Extract latest DBC2CSV release
      if: ${{ steps.check.outputs.skip != 'true' }}
      run: |
        unzip -q *.zip
        chmod +x DBC2CSV

    - name: Checkout latest WoWDBDefs
      if: ${{ steps.check.outputs.skip != 'true' }}
      uses: actions/checkout@v4
      with:
        repository: wowdev/WoWDBDefs
        path: ./WoWDBDefs

    - name: Move the definitions to the correct folder
      if: ${{ steps.check.outputs.skip != 'true' }}
      run: |
        cp -rf ./WoWDBDefs/definitions/* ./definitions/

    - name: Download latest hotfix
      if: ${{ steps.check.outputs.skip != 'true' }}
      id: hotfix
      run: |
        hotfixoutput="extracts/${{ inputs.PRODUCT }}/db2"
        hotfixname="DBCache.bin"
        hotfixfile="$hotfixoutput/$hotfixname"
        hotfixfiletemp="$hotfixfile.temp"
        hotfixbranch="hotfixes"
        hotfixlocale="enUS"
        hotfixpath="${{ inputs.PRODUCT }}/$hotfixlocale/$hotfixname"
        curl -sfL "https://github.com/${{ github.repository }}/raw/$hotfixbranch/$hotfixpath" -o "$hotfixfiletemp" || true
        if [[ $? -eq 0 && -f "$hotfixfiletemp" && -s "$hotfixfiletemp" ]]; then
          mv -f "$hotfixfiletemp" "$hotfixfile"
          echo "Successfully applied hotfix: $hotfixpath"
          echo "active=true" >> $GITHUB_OUTPUT
        else
          rm -f "$hotfixfiletemp"
          echo "Unable to apply hotfix: $hotfixpath"
        fi

    - name: Run DBC2CSV
      id: dbc2csv
      if: ${{ steps.check.outputs.skip != 'true' }}
      working-directory: extracts/${{ inputs.PRODUCT }}/db2
      run: |
        tempfile=$(mktemp)
        run_dbc2csv() {
          ../../../DBC2CSV . &> "$tempfile"
          local runExitCode=$?
          local table_count=0
          local table_count_error=0
          local table_count_bounds_error=0
          while IFS= read -r line; do
            if [[ $line == *"Exporting table"* ]]; then
              (( table_count++ ))
            elif [[ $line == *"Failed to export"* ]]; then
              if [[ $line == *"Index was outside the bounds of the array"* ]]; then
                (( table_count_error++ ))
                (( table_count_bounds_error++ ))
              elif ! [[ $line == *"No rows found"* ]]; then
                (( table_count_error++ ))
              fi
            fi
          done < "$tempfile"
          local table_count_success=$(( table_count - table_count_error ))
          echo "$runExitCode,$table_count,$table_count_success,$table_count_error,$table_count_bounds_error"
        }
        output=$(run_dbc2csv)
        cat "$tempfile"
        IFS=',' read -r runExitCode table_count table_count_success table_count_error table_count_bounds_error <<< "$output"
        echo "DBC2CSV exited with code $runExitCode: $table_count files scanned. $table_count_success converted. $table_count_error failed."
        if [[ "${{ steps.hotfix.outputs.active }}" == "true" ]]; then
          if [[ $runExitCode -ne 0 || $table_count -le 100 || $table_count_success -le $(( table_count / 2 )) ]]; then
            echo "Trying to recover by re-trying without the hotfix."
            rm -f *.bin
            output=$(run_dbc2csv)
            cat "$tempfile"
            IFS=',' read -r runExitCode table_count table_count_success table_count_error table_count_bounds_error <<< "$output"
            echo "DBC2CSV exited with code $runExitCode: $table_count files scanned. $table_count_success converted. $table_count_error failed."
          fi
        fi
        find . -type f ! -iname "*.csv" -delete
        rm -f "$tempfile"
        if [[ $table_count_bounds_error -gt 0 ]]; then
          echo "Due to $table_count_bounds_error out of bounds errors the script will skip commiting the build."
          echo "skip=true" >> $GITHUB_OUTPUT
        fi

    - name: Create branch for release
      if: ${{ steps.check.outputs.skip != 'true' && steps.dbc2csv.outputs.skip != 'true' }}
      run: |
        set -euo pipefail
        cd extracts
        product=${{ inputs.NAME }}
        folder=${{ inputs.PRODUCT }}
        build=$(basename $(readlink -f "${folder}"))
        message="${product} ${build}"
        tag="${product}_${build}"
        cd "${folder}/db2"
        tmpzip="/tmp/${build}.zip"
        if ! zip -q "${tmpzip}" *.csv; then
          echo "Failed to create zip file" >&2
          exit 1
        fi
        cd ../../../
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com
        cleanup() {
          find . -maxdepth 1 -mindepth 1 ! -name .git -exec rm -rf {} +
        }
        checkout_branch() {
          local branch_name=$1
          git fetch --prune origin
          if git show-ref --quiet "refs/remotes/origin/${branch_name}"; then
            echo "Re-using existing branch..."
            git fetch origin "${branch_name}"
            git checkout -b "${branch_name}" "origin/${branch_name}"
            git pull --rebase origin "${branch_name}"
            git rm -rfq .
            cleanup
          else
            echo "Creating new branch..."
            cleanup
            git rm -rfq .
            git checkout --orphan "${branch_name}"
            git commit --allow-empty --message "Initialize"
            git push --set-upstream origin "${branch_name}"
          fi
        }
        latest_branch="release/${product}_latest"
        checkout_branch "${latest_branch}"
        echo "Extract the ZIP then queue the files..."
        unzip -q "${tmpzip}"
        git add -v .
        echo "Checking if there are changes to be commited and pushed..."
        if [[ -n $(git status --porcelain) ]] || ! git diff --quiet; then
          if git commit --message "${message}" >/dev/null 2>&1; then
            echo "Commiting, tagging and pushing..."
            git tag "${tag}"
            git push --force-with-lease --set-upstream origin "${latest_branch}" --tags
          else
            echo "Unable to commit."
          fi
        else
          echo "Nothing to commit."
        fi
        echo "Done!"
